# Generated by Django 5.2.5 on 2025-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'clasificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenLibro',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imagen_libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_intercambio', models.CharField(max_length=255)),
                ('fecha_intercambio', models.DateField(blank=True, null=True)),
                ('estado_intercambio', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Completado', 'Completado')], default='Pendiente', max_length=10)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intercambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('anio_publicacion', models.PositiveSmallIntegerField()),
                ('autor', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField()),
                ('descripcion', models.TextField()),
                ('editorial', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('tipo_tapa', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoActividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('ip_origen', models.CharField(max_length=45)),
                ('dispositivo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'seguimiento_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('dispositivo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificacionUsuario',
            fields=[
                ('id_verificacion', models.AutoField(primary_key=True, serialize=False)),
                ('documento_identidad', models.CharField(max_length=255, unique=True)),
                ('fecha_verificacion', models.DateField()),
                ('verificado_por', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'verificacion_usuario',
                'managed': False,
            },
        ),
    ]
