# Generated by Django 5.2.6 on 2025-10-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_delete_notificacion_delete_seguimientoactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroSolicitudesVistas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ultimo_visto_id_intercambio', models.IntegerField(default=0)),
                ('visto_por_ultima_vez', models.DateTimeField()),
            ],
            options={
                'db_table': 'libro_solicitudes_vistas',
                'managed': False,
            },
        ),
    ]
