# Generated by Django 5.2.5 on 2025-09-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={},
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='core.usuario'),
        ),
    ]
