# Generated by Django 5.2.5 on 2025-09-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial_unmanaged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='SeguimientoActividad',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.DeleteModel(
            name='VerificacionUsuario',
        ),
    ]
