# Generated by Django 5.2.5 on 2025-09-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_unmanaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoActividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('ip_origen', models.CharField(max_length=45)),
                ('dispositivo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'seguimiento_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('dispositivo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificacionUsuario',
            fields=[
                ('id_verificacion', models.AutoField(primary_key=True, serialize=False)),
                ('documento_identidad', models.CharField(max_length=255, unique=True)),
                ('fecha_verificacion', models.DateField()),
                ('verificado_por', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'verificacion_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='core.usuario')),
            ],
            options={
                'db_table': 'password_reset_token',
                'managed': True,
            },
        ),
    ]
